### ISSUE TITLE
Preferences: allow specifying preferred video/audio format

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#295]
Right now all video and audio files are automatically converted to mp4 and mp3, respectively. Support ogg and webm too.

**Comment by erikyo** [comment]
+1 for webm! I experienced in the past being forced to use this format since it is the only one that allows frame-by-frame control of videos (https://dataloop.ai/docs/webm-and-frame-accurate-annotation)... So the possibility of converting to this format is welcome (webm was the reason why i created [this repo](https://github.com/erikyo/wp-wasm-encoder) some times ago)
