### ISSUE TITLE
AVIF thumbnail generation not working

### ISSUE THREAD

**Issue by gyurmey2** [swissspidy/media-experiments#487]
Hi, I started testing the plugin, but for some reason images that should be in AVIF format are [generated to PNG format](https://app.instawp.io/wordpress-auto-login?site=$2y$10$5xoVR3x9jAtsZ8djIPCeleJxC1MJj9NZKwfOLh/G7MA/hq2.xl0e6).

**Comment by swissspidy** [comment]
Did you choose AVIF as the desired output fornat in the preferences?

**Comment by gyurmey2** [comment]
Yes, exactly. You can also please test it using the link I provided.

**Comment by swissspidy** [comment]
I cannot reproduce this issue on my own website.

This InstaWP link you shared doesn't work properly. InstaWP is breaking the loading of some scripts and styles.

<img width="792" alt="Screenshot 2024-06-01 at 11 37 17" src="https://github.com/swissspidy/media-experiments/assets/841956/5c5b2331-f73f-43cf-a024-d4c39d1ba7a8">

Instead of loading scripts it responds with an interstitial page, as you can see from this screenshot:

<img width="1162" alt="Screenshot 2024-06-01 at 11 38 01" src="https://github.com/swissspidy/media-experiments/assets/841956/48dcf7c6-b447-4eb7-9810-4207e4cea194">

Please try the plugin somewhere else while InstaWP is broken like this.

**Comment by gyurmey2** [comment]
You're right, something was wrong.

[In this case it should be ok.](https://allowletters.s1-tastewp.com/wp-admin)
fenr3
PZLolf9ohcI

**Comment by swissspidy** [comment]
Works like a charm on that site for me, the JPG images is converted to AVIF.

**Comment by swissspidy** [comment]
Huh, interesting, it looks like the thumbnails didn‘t convert to the right format. I‘ll take a closer look.

**Comment by swissspidy** [comment]
Looks like it's an issue with the image library preference.

A workaround for now is to change it to libvips (which is recommended anyway):

<img width="527" alt="Screenshot 2024-06-02 at 17 35 41" src="https://github.com/swissspidy/media-experiments/assets/841956/b97d1098-5e9b-44cc-b06b-7656f424ac36">

**Comment by gyurmey2** [comment]
I understand and thank you. I deliberately chose "Browser" because it completely solves [this issue](https://github.com/WordPress/gutenberg/issues/45714).

**Comment by swissspidy** [comment]
You mean because the image processing runs in the browser? well, libvips also runs in the browser :) So you won't have any memory issues.

"Browser" just means it uses the browser's built-in Canvas API to resize images, whereas libvips runs libvips via WebAssembly in a web worker and is much faster.

Please give it a try :)

If you are worried about server memory issues, the important setting is the "thumbnail generation" part and whether you choose "client-side" or "server-side" there. server-side would be the issue.

I'll see if I can make the wording a bit more clearer.

**Comment by gyurmey2** [comment]
Thanks for the explanation. And I think I need to take another look at this ;)

The plugin itself is really amazing!
